alert("Babbyyyyyy")
alert("Pansinin mo koo!!!!! tamaa na larooo!")
alert("puro ka drugs ")
alert("ako namaaaannnn")
alert("I misss youuu babyyy kooo")
alert("mine ka munaa tuloy mo nalang yan tomorrow")
alert("waabyuuuu ")